language: java
dist: trusty
sudo: false

-os: linux

jdk:
  - oraclejdk9

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

env:
  - TEST=test
  - TEST=spotbugs:check

jobs:
  include:
      script: "mvn $TEST -B"
