language: java
dist: trusty

jdk:
  - oraclejdk9
  - oraclejdk8

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

matrix:
  include:
    - os: linux
      env:
        - Junit
      script:
        - mvn test -B
    - os: linux
      env:
        - Spotbugs
      script:
        - mvn spotbugs:check
